version: '3'
services: 
    db:
        image: mysql:5.7
        container_name: mysql_host
        environment: 
            MYSQL_ROOT_PASSWORD: secret
        volumes: 
            - ./db/data:/var/lib/mysql